import Image from 'next/image'; import Link from 'next/link'; import {ArrowDown,ArrowRight,ArrowUpRight,MapPin,Phone} from '@phosphor-icons/react/dist/ssr'; import {Header} from '@/components/Header';import {Footer} from '@/components/Footer';import {Gallery} from '@/components/Gallery';import {Hero} from '@/components/Hero';import {ConversionBar} from '@/components/ConversionBar';import {BookingEngine} from '@/components/BookingEngine';import {siteConfig,contactHref,hasContact,developerLinks,placeMapHref} from '@/data/site';import {images} from '@/data/images';import {rooms} from '@/data/rooms';
const places=[['Abant Gölü','Dört mevsim değişen göl manzarası ve orman yürüyüşleri.'],['Yedigöller','Bolu’nun kalbinde göller, şelaleler ve renkli ormanlar.'],['Gölcük Tabiat Parkı','Şehir merkezinden doğaya uzanan huzurlu bir rota.'],['Kartalkaya','Kış sporları ve yükseklerde büyüleyici dağ atmosferi.'],['Mudurnu & Göynük','Tarihi konaklar, sakin sokaklar ve köklü yerel kültür.'],['Bolu Yaylaları','Aladağ, Seben ve Kıbrıscık çevresinde tertemiz yayla havası.']];
const reviews=[{name:'Mustafa Ö.',text:'Bolu merkezde konaklayıp çevredeki doğa rotalarına ulaşmak çok rahattı. Sade ve huzurlu bir deneyim.'},{name:'Sena K.',text:'Sabah Gölcük’e, ertesi gün Abant’a uzanan planımız için merkez konumu iyi bir başlangıç oldu.'},{name:'Mehmet G.',text:'Yayla gezisinin ardından dinlenebileceğimiz sıcak ve modern bir şehir oteli deneyimi hayal ettik.'},{name:'Özlem E.',text:'Kahvaltı sonrası Gölcük’e uzandık; odaya döndüğümüzde şehir otelinin sakinliği iyi geldi.'},{name:'Hüseyin B.',text:'Yedigöller rotası için merkezde kalmak pratikti. Oda düzeni sade, karşılama ise içten ve rahattı.'}];
const site={name:siteConfig.brandName,location:siteConfig.location,phone:siteConfig.phone,phoneHref:contactHref('phone'),whatsapp:contactHref('whatsapp'),instagram:contactHref('instagram'),maps:contactHref('maps'),distances:siteConfig.distances};
// No LodgingBusiness structured data: this is a portfolio demo, not a real business.
export default function Home(){return <><Header/><ConversionBar/><main><Hero/>
<section className="facts">{site.distances.map(x=><div key={x.label}><strong>{x.value}</strong><span>{x.label}</span></div>)}</section><BookingEngine/>
<section id="hakkimizda" className="section intro"><div className="image-wrap tall"><Image src={images.exterior} alt="Bolu doğasında Mavi Kadraj Otel atmosferi" fill sizes="(max-width: 800px) 90vw, 45vw"/></div><div className="copy"><span className="eyebrow">Mavi Kadraj’a hoş geldiniz</span><h2>Bolu’yu yaşamak için<br/><em>doğru yerden başlayın.</em></h2><p>Mavi Kadraj Otel, Bolu Merkez’de şehir konforuyla doğa keşfini buluşturur. Abant’tan Yedigöller’e, Gölcük’ten yemyeşil yaylalara uzanan rotaların başlangıç noktasıdır.</p><a className="text-link" href="#kesfet">Bolu rotalarını keşfet <ArrowRight/></a></div></section>
<section id="odalar" className="section rooms"><div className="section-head"><div><span className="eyebrow">Doğa sonrası sade konfor</span><h2>Size Uygun Odayı Bulun</h2></div><p>Bolu Merkez’de, keşif dolu bir günün ardından dinlenebileceğiniz konaklama seçenekleri.</p></div><div className="room-grid">{rooms.map((r,i)=><article className="room-card" key={r.slug}><Link href={`/odalar/${r.slug}`} className="room-image"><Image src={r.image} alt={r.name} fill sizes="(max-width: 800px) 90vw, 33vw"/><span>0{i+1}</span></Link><div className="room-body"><div><small>{r.capacity}</small><h3>{r.name}</h3></div><ul>{r.features.slice(0,3).map(f=><li key={f}>{f}</li>)}</ul><div className="room-actions"><Link href={`/odalar/${r.slug}`}>Odayı incele <ArrowRight/></Link><a href="#rezervasyon">Rezervasyon yap</a></div></div></article>)}</div></section>
<section id="kesfet" className="experience"><div className="section experience-title"><span className="eyebrow light">Doğa rotaları kapınızda</span><h2>Kapıdan Çık.<br/><em>Bolu Başlasın.</em></h2></div><div className="place-strip">{places.map((p,i)=><article key={p[0]}><Image src={images.destinations[i%images.destinations.length]} alt={p[0]} fill sizes="(max-width: 700px) 80vw, 30vw"/><div><span>0{i+1}</span><h3>{p[0]}</h3><p>{p[1]}</p><a href={placeMapHref(p[0])} target="_blank" rel="noopener noreferrer">Haritada gör <ArrowUpRight/></a></div></article>)}</div></section>
<section className="section route"><div><span className="eyebrow">Merkezden doğaya</span><h2>Bolu’nun Tam<br/><em>Merkezindesiniz.</em></h2><p>Şehir içindeki ihtiyaçlarınıza yakın, göllere, tabiat parklarına ve yaylalara uzanan yolların merkezindesiniz.</p>{hasContact('maps')?<a className="btn dark" href={site.maps}><MapPin/> Yol Tarifi Al</a>:<a className="btn dark" href={placeMapHref('Bolu Merkez')} target="_blank" rel="noopener noreferrer"><MapPin/> Bolu’yu Haritada Gör</a>}</div><ol>{[siteConfig.brandName,'Bolu Merkez','Gölcük Tabiat Parkı','Abant Gölü','Yedigöller'].map((x,i)=><li key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b>{i<4&&<ArrowDown/>}</li>)}</ol></section>
<section id="galeri" className="section"><div className="section-head"><div><span className="eyebrow">Bolu’dan bir kadraj</span><h2>Doğa, Şehir ve Mavi Kadraj</h2></div><p>Odalar, kahvaltı, Abant, Yedigöller, Gölcük ve Bolu’nun yüksek yaylaları.</p></div><Gallery/></section>
<section className="section testimonials"><span className="eyebrow">Demo misafir anlatıları</span><h2>Konaklama Deneyiminden Notlar</h2><div className="review-grid">{reviews.map(r=><blockquote key={r.name}><span>“</span><p>{r.text}</p><footer>{r.name}</footer></blockquote>)}</div><p className="demo-note">Bu metinler portföy tasarım gösterimi içindir; gerçek misafir veya Google yorumları değildir.</p></section>
<section className="cinematic"><Image src={images.hero} alt="Sonbaharda Abant Gölü ve Bolu ormanları" fill sizes="100vw"/><div className="hero-shade"/><div><span className="eyebrow light">Sıradaki rota: Bolu</span><h2>Doğa Sizi Bekliyor.</h2><p>Bolu Merkez’de konaklayın; gölleri, ormanları ve yaylaları keşfedin.</p><div className="actions"><a className="btn white" href="#rezervasyon">Rezervasyon Yap <ArrowUpRight/></a>{hasContact('phone')&&<a className="text-link light" href={site.phoneHref}><Phone/> Bizi Arayın</a>}</div></div></section>
<section id="iletisim" className="section contact"><div><span className="eyebrow">İletişim</span><h2>Merkezde buluşalım.</h2><p>{siteConfig.demo?'Canlı bir projede bu alanda otelin telefonu, WhatsApp hattı, sosyal medya hesapları ve konumu yer alır.':'Planınızı anlatın, size uygun oda için birlikte bakalım.'}</p></div>
{siteConfig.demo?<div className="contact-card demo-card"><span className="eyebrow">Örnek proje</span><h3>Oteliniz için benzer bir site</h3><p>{site.name}, {siteConfig.developerName} tarafından otel ve pansiyon işletmeleri için hazırlanmış bir demo çalışmasıdır. Tasarım, oda sayfaları ve rezervasyon akışı işletmenize göre uyarlanabilir.</p><a href={developerLinks.project}>Projeyi {siteConfig.developerName}’te inceleyin<ArrowUpRight/></a><a href={developerLinks.contact}>İşletmeniz için görüşelim<ArrowUpRight/></a></div>
:<div className="contact-card"><h3>{site.name}</h3><p>{site.location}</p>{hasContact('phone')&&<a href={site.phoneHref}>{site.phone}<ArrowUpRight/></a>}{hasContact('whatsapp')&&<a href={site.whatsapp}>WhatsApp<ArrowUpRight/></a>}{hasContact('instagram')&&<a href={site.instagram}>Instagram<ArrowUpRight/></a>}{hasContact('maps')&&<a href={site.maps}>Google Maps<ArrowUpRight/></a>}</div>}</section></main><Footer/></>}
