import Database from 'better-sqlite3';import path from 'node:path';import fs from 'node:fs';
const dbDir=process.env.VERCEL?path.join('/tmp','mavi-kadraj-data'):path.join(process.cwd(),'data');fs.mkdirSync(dbDir,{recursive:true});
const db=new Database(path.join(dbDir,'booking.sqlite'));db.pragma('journal_mode = WAL');db.pragma('foreign_keys = ON');db.pragma('busy_timeout = 5000');
db.exec(`
CREATE TABLE IF NOT EXISTS room_types(id INTEGER PRIMARY KEY AUTOINCREMENT,room_type TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT NOT NULL,total_rooms INTEGER NOT NULL CHECK(total_rooms>=0),capacity_adults INTEGER NOT NULL,capacity_children INTEGER NOT NULL,base_price INTEGER NOT NULL,active INTEGER NOT NULL DEFAULT 1,images TEXT NOT NULL,features TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS rooms(id INTEGER PRIMARY KEY AUTOINCREMENT,room_type_id INTEGER NOT NULL,room_number TEXT NOT NULL UNIQUE,active INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(room_type_id) REFERENCES room_types(id));
CREATE TABLE IF NOT EXISTS reservations(id INTEGER PRIMARY KEY AUTOINCREMENT,reservation_number TEXT NOT NULL UNIQUE,room_type_id INTEGER NOT NULL,room_id INTEGER NOT NULL,check_in TEXT NOT NULL,check_out TEXT NOT NULL,adults INTEGER NOT NULL,children INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL CHECK(status IN ('PENDING','CONFIRMED','CANCELLED')),payment_status TEXT NOT NULL DEFAULT 'UNPAID',payment_method TEXT,total_amount INTEGER NOT NULL,currency TEXT NOT NULL DEFAULT 'TRY',notes TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(room_type_id) REFERENCES room_types(id),FOREIGN KEY(room_id) REFERENCES rooms(id),CHECK(check_out>check_in));
CREATE TABLE IF NOT EXISTS reservation_guests(id INTEGER PRIMARY KEY AUTOINCREMENT,reservation_id INTEGER NOT NULL,first_name TEXT NOT NULL,last_name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT NOT NULL,is_primary INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(reservation_id) REFERENCES reservations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS blocked_dates(id INTEGER PRIMARY KEY AUTOINCREMENT,room_id INTEGER,room_type_id INTEGER,start_date TEXT NOT NULL,end_date TEXT NOT NULL,reason TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(room_id) REFERENCES rooms(id),FOREIGN KEY(room_type_id) REFERENCES room_types(id),CHECK(end_date>start_date));
CREATE INDEX IF NOT EXISTS idx_reservation_dates ON reservations(room_id,check_in,check_out,status);CREATE INDEX IF NOT EXISTS idx_blocked_dates ON blocked_dates(room_id,start_date,end_date);
`);
const seed=db.transaction(()=>{const count=(db.prepare('SELECT COUNT(*) count FROM room_types').get() as {count:number}).count;if(count)return;
const types=[
 ['Deluxe Orman Oda','deluxe-orman','Doğal dokular ve sakin orman tonlarıyla iki kişilik ferah oda.',4,2,1,250000,['/images/boutique-room.png'],['Klima','Yüksek hızlı Wi‑Fi','Özel banyo','Kahvaltı']],
 ['Superior Aile Odası','superior-aile','Aileler ve uzun konaklamalar için geniş, işlevsel yaşam alanı.',3,3,2,340000,['/images/boutique-room.png'],['Klima','Yüksek hızlı Wi‑Fi','Özel banyo','Oturma alanı']],
 ['Mavi Kadraj Suit','mavi-kadraj-suit','Bolu doğasından ilham alan, ayrı dinlenme alanlı özel suit.',2,2,2,420000,['/images/boutique-room.png'],['Klima','Yüksek hızlı Wi‑Fi','Özel banyo','Mini bar']]
];const insertType=db.prepare('INSERT INTO room_types(room_type,slug,description,total_rooms,capacity_adults,capacity_children,base_price,images,features) VALUES(?,?,?,?,?,?,?,?,?)');const insertRoom=db.prepare('INSERT INTO rooms(room_type_id,room_number) VALUES(?,?)');let seq=101;for(const t of types){const info=insertType.run(t[0],t[1],t[2],t[3],t[4],t[5],t[6],JSON.stringify(t[7]),JSON.stringify(t[8]));for(let i=0;i<(t[3] as number);i++)insertRoom.run(info.lastInsertRowid,String(seq++));}});seed();
export default db;
